# Generated by Django 4.2.7 on 2024-01-17 06:00

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0061_alter_emergency_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="IGPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Igps", models.CharField(max_length=200)),
                ("Message", models.CharField(max_length=400)),
                ("From", models.CharField(max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=myapp.models.filepath
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigatorRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="publicRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ServicesOfPolice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=myapp.models.filepath
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TandC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Term", models.CharField(max_length=200)),
            ],
        ),
    ]
